# Generated by Django 5.0.3 on 2024-03-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
